steps:
  - name: Install Setuptools
    run: pip install setuptools
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: ${{ matrix.python-version }}
  - name: Install Dependencies
    run: |
      pip install -r requirements.txt
  - name: Run setup.py
    run: |
      python setup.py install